In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
print(arr)

[1 2 3 4 5]


In [2]:
arr.shape

NameError: name 'arr' is not defined

In [20]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
arr=np.array([my_list1,my_list2])

In [21]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [8]:
arr.shape

(2, 5)

In [16]:
arr.reshape(1,10)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6]])

In [11]:
arr.shape

(2, 5)

<b>Indexing</b>

In [37]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [18]:
arr[3]

4

In [22]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [27]:
arr[0:,0:2]

array([[1, 2],
       [2, 3]])

In [28]:
arr[1:,3:]

array([[5, 6]])

In [32]:
arr=np.arange(0,10,2)

In [33]:
arr

array([0, 2, 4, 6, 8])

In [36]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [40]:
##copy function and broadcasting
arr[3:]=100

In [41]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [42]:
arr1=arr

In [43]:
arr1[3:500]

array([100, 100, 100, 100, 100, 100])

In [44]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [45]:
arr1=arr.copy()

In [46]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 100 100 100 100 100 100]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [47]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [48]:
##some conditions useful in exploratory data analysis

val=2

In [49]:
val

2

In [50]:
arr<2

array([ True, False, False, False, False, False, False, False, False])

In [51]:
arr<3

array([ True,  True, False, False, False, False, False, False, False])

In [52]:
arr[arr<6]

array([1, 2, 3])

In [53]:
np.ones

<function numpy.ones(shape, dtype=None, order='C')>

In [56]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [57]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
np.random.rand(3,3)

array([[0.01522944, 0.02940588, 0.73734622],
       [0.72547994, 0.54687816, 0.41317189],
       [0.13526969, 0.2864754 , 0.63030013]])

In [59]:
arr_ex=np.random.randn(4,4)
arr_ex

array([[ 0.26664751, -0.25302375, -1.07442338, -1.18286965],
       [ 0.97967798, -0.02669496,  0.60795943,  0.04044985],
       [ 1.15618637,  2.12841821,  1.47212581,  1.36378904],
       [ 0.31038054, -1.48538655,  0.5977517 , -0.66449702]])

In [61]:
np.random.randint(0,100,8).reshape(2,4)

array([[64, 84, 30, 33],
       [ 6,  9, 74, 29]])

In [62]:
np.random.random_sample((1,5))

array([[0.89507215, 0.38132765, 0.26668661, 0.47704088, 0.16880718]])